version: 2
project_name: E5SubBot

builds:
  - main: .
    binary: E5SubBot
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/Debcharon/E5SubBot/internal/buildinfo.Version=v{{.Version}} -X github.com/Debcharon/E5SubBot/internal/buildinfo.Commit={{.FullCommit}} -X github.com/Debcharon/E5SubBot/internal/buildinfo.Date={{.Date}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - README_CN.md
      - config.yml.example
      - LICENSE

checksum:
  name_template: E5SubBot_checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
